language: python
python:
  - '3.6'
install:
  - python setup.py install
  - mv /tmp/mua-config.yml.sample ~/mua-config.yml
script:
  - tests/smoke.sh
deploy:
  provider: pypi
  user: max_lobur
  password:
    secure: HP7MC78bQ6ceJYHXGqyFfr+ogPVNmvirb4nFhKRrJ6bKm7/UXfhNmcL1FpeEnq43QbrxTOkO9pe1LZxNHoPOJqHj4iBqspbrdBDz5IoqudtnfVmjYJ1JNstskymaOouBtyCb+zyviGTbqaafnWP+a+n5oZZ+5TTgdlMzOUMkrwicDkxCVx6rQ32T5/ZPbKolc6E07+39Sc2spEukTuLxxxYH1B+/w8fBcIfgp7RpntcCFMleSQiFdRHNhrD74ge6j0Iz27eF1ESO7CLhv4aT9DvYbv4RUfxpNO+5xk3/bZGlwFEYLRmRth8Kf43e3sSeLy+QBsYyR2sdCSLhr73aTXH8A1vu2t5k06S+lEIq3kLcV0T082Ag0vKxfDGeoftIQt6tq/Ld18Jo3zEcLeduWMLEfGr75VGGJXJvSaJK2zsVjCvov1491wnA7YDtxSuLp+T9a16i29x0jHjTK48zOBaD5/bfkQgru8WBtYCikep4SbJMDQ2khfHCFG3VVihf4M443kzxL3bDZmlVgZpSyKW+7UYFxSHTAh01qzbt/9+gclcJdGjPaIN+xqliybBmusVRPQGwF0Ib7W1syu2NVbkiQwBwzhkQVzX08O7QWAXrvHpQQsGyF7r+9rjCtmJt9wxoSHvgZDHJH6zwwMyFElB5Py1YjJzPhhsMJGm6RoM=
  on:
    tags: true
