language: python
python:
- '3.6'
install:
- python setup.py install
- mv /tmp/mua-config.yml.sample ~/mua-config.yml
script:
- tests/smoke.sh
deploy:
  provider: pypi
  user: max_lobur
  password:
    secure: PfhQUkoCvxJAJ1NACw7Kqf/WOP+ovFIkhYB/RV5ohbXVgdbTnlgpr087pxkTgwayRcR7J+4uvOR12dQO2DThcgfeelurhd8V7hTvJRKcnQjp/1jTqGnNr45RntlNLQcFyxwkWmpDsdM+RAz7fibl+sUU695n8aTKzfa6l952QGu44WlrcpGr+v/19tp7dRilgllSpr7Y9cOZNqYm/zuXnj2COZSR/0n3TSXseMMUkIEAPGZ8yCpGhNc2WLb/nnXJU8RPB4k2G176g98JpcTLKI0IsFwqzQSkAeqRIaWpcPTpZWwDql7c7IZTUrQ4x7Srr6/FQ7jXEUcgpFR4vxvvX3IiqkWBgzxt3SFlMsafEqkEPtb0s+dUaW+7DTDczgIH4tDbYUaQpX70huQuBrUlYDtrTgZ6JFFgrF118c0XC0gyyaj9f57Py/M6svfuob6ZQzHj1hWlwCjcMD6j8tDLu13yYwIMypFsH+x8M5x/rD6AC5+4M1lBIGevbqLTltAq2JADLTnJIR78u08oGR7uYYOhTqH9/W84dkq5AYb9tZpCa+akhbwaLt6LXe5+gsZZwGddrBnREH4j0VhYSlUz9dy5trdpa7spqfIij0mW+x/9tEgqQ8TQxojkrsg4D8iPhycl66EOdi++cCnGLtCFOqi/RwkO60QgWUqs2NtUKoc=
  on:
    tags: true
